language: cpp

#Which branches to build. Currently set for master and any tag
#branches:
#  only:
#  - master
#  - /v[0-9].*$/

# Notification settings
notifications:
  email: false
    # Default recipients are those with push or admin permissions of the repo
    #recipients:
    #on_success: never # default: change
    #on_failure: always # default: always

# Get the repository
git:
  # Depth of commits to grab. Less is faster
  depth: 3
  # Init submodules
  #submodules: false

# Matrix of operating systems and dependencies
matrix:
  include:
    - os: linux
      sudo: required
      dist: xenial
      services: xvfb
      addons:
        apt:
          update: true
          sources:
            - sourceline: ppa:beineri/opt-qt-5.11.1-xenial
          packages:
            - libgl1-mesa-dev
            - qt511base
#    - os: osx
#      addons:
#        brew:
#          update: true
#          packages:
#            - qt5
#      # Brew doesn't automatically set qt5 bins to PATH anymore
#      env: PATH="${PATH}:/usr/local/opt/qt/bin"    
#    - os: osx
#      osx_image: xcode10
#      addons:
#        brew:
#          update: true
#          packages:
#            - qt5
#      # Brew doesn't automatically set qt5 bins to PATH anymore
#      env:
#        - PATH="${PATH}:/usr/local/opt/qt/bin"
#        - osx_image="xcode10"
#    - os: windows

# OPTIONAL - which components to cache 
#cache components:

# Stuff to do before installing the dependencies          
# non-zero exit status: build status returns failed and exits immediately
before_install:
 - . $TRAVIS_BUILD_DIR/travis/travis_before_install.sh

# Install dependencies here      
# non-zero exit status: build status returns failed and exits immediately
install:
  - . $TRAVIS_BUILD_DIR/travis/travis_install.sh

# OPTIONAL - After dependencies but before the build step
# non-zero exit status: build status returns failed and exits immediately
#before_script:

# The build step
# non-zero exit status: build status returns failed, but continues to run. Intended for the after_failure step
script:
  - . $TRAVIS_BUILD_DIR/travis/travis_script.sh

# OPTIONAL - Cleaning up the cache
#before_cache:

# What to do if success or failure
# non-zero exit status: build status returns failed but continues running
after_success:
  # cd to a next level directory because of the relative path in /src/CinScopeTest.cpp
  - cd $TRAVIS_BUILD_DIR/src 
  - $TRAVIS_BUILD_DIR/cinema_scope_test
#after_failure:

# OPTIONAL - Steps before deployement. Runs for each deployement if there are multiple deployements
# non-zero exit status: build status returns failed but continues running
#before_deploy:
#  git clone https://github.com/${TRAVIS_REPO_SLUG}.git ${TRAVIS_TAG} && \
#    cd ${TRAVIS_TAG} && git checkout ${TRAVIS_TAG} && cd ../ && \
#    zip -r ${TRAVIS_TAG}.zip ${TRAVIS_TAG} && \
#    tar czf ${TRAVIS_TAG}.tar.gz ${TRAVIS_TAG} 

# OPTIONAL - Deployment
# non-zero exit status: build status returns failed but continues running
# This deploys a zip and a tarball to Github Releases if it is a tagged push request
#deploy:
#  provider: releases
#  api_key: "GITHUB OATH TOKEN"
#  file:
#    - "${TRAVIS_TAG}.zip"
#    - "${TRAVIS_TAG}.tar.gz"
#  skip_cleanup: true
#  on:
#    tags: true

# OPTIONAL - Steps after deployement. Runs for each deployement if there are multiple deployements
# non-zero exit status: build status returns failed but continues running
#after_deploy:

# Steps after script
# non-zero exit status: build status returns failed but continues running
#after_script:
